# -*- coding: utf-8 -*-
"""Sc_mini.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16asoGkyWKvG2YdWQpXHi0Y6r_BNJUUDW
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import accuracy_score, confusion_matrix
import pickle

df = pd.read_csv("continuous dataset.csv", parse_dates=["datetime"])

print(df.head())
print(df.head())
print(df.columns)

df["hour"] = df["datetime"].dt.hour
df["dayofweek"] = df["datetime"].dt.day_of_week
df["month"] =   df["datetime"].dt.month

df["demand_class"] = pd.qcut(df["nat_demand"], q=3, labels=[0,1,2])

features = [
    "T2M_toc", "QV2M_toc", "TQL_toc", "W2M_toc",
    "T2M_san", "QV2M_san", "TQL_san", "W2M_san",
    "T2M_dav", "QV2M_dav", "TQL_dav", "W2M_dav",
    "Holiday_ID", "holiday", "school",
    "hour", "dayofweek", "month"
]

X = df[features].values
y = df["demand_class"].astype(int).values

scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)

from sklearn.decomposition import PCA

pca = PCA(n_components=0.95)
X_scaled = pca.fit_transform(X_scaled)

n_classes = len(np.unique(y))
prototypes_per_class = 5
n_features = X_scaled.shape[1]

total_prototypes = n_classes * prototypes_per_class

def get_proto_labels():
    labels = []
    for c in range(n_classes):
        labels += [c] * prototypes_per_class
    return np.array(labels)

proto_labels = get_proto_labels()

def create_individual():
    return np.random.uniform(
        low=np.min(X_scaled, axis=0),
        high=np.max(X_scaled, axis=0),
        size=(total_prototypes, n_features)
    )

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

X_train, X_val, y_train, y_val = train_test_split(
    X_scaled, y, test_size=0.2, random_state=42
)

def train_lvq(X, y, prototypes, proto_labels, lr=0.1, epochs=100):

    for epoch in range(epochs):

        indices = np.random.permutation(len(X))

        for i in indices:

            x = X[i]
            label = y[i]

            distances = np.linalg.norm(prototypes - x, axis=1)

            winner = np.argmin(distances)

            if proto_labels[winner] == label:
                prototypes[winner] += lr * (x - prototypes[winner])
            else:
                prototypes[winner] -= lr * (x - prototypes[winner])

        lr *= 0.9

    return prototypes

def fitness(individual):
    proto_copy = individual.copy()

    trained_proto = train_lvq(
        X_train, y_train,
        proto_copy,
        proto_labels,
        lr=0.05,
        epochs=15
    )

    preds = predict_lvq(X_val, trained_proto, proto_labels)

    return accuracy_score(y_val, preds)

def selection(pop, fitnesses, k=3):
    selected = []
    for _ in range(len(pop)):
        idx = np.random.choice(len(pop), k)
        best = idx[np.argmax([fitnesses[i] for i in idx])]
        selected.append(pop[best])
    return selected

def crossover(p1, p2):
    child = p1.copy()
    mask = np.random.rand(*p1.shape) < 0.5
    child[mask] = p2[mask]
    return child

def mutation(ind, rate=0.1):
    noise = np.random.normal(0, 0.05, ind.shape)
    mask = np.random.rand(*ind.shape) < rate
    ind[mask] += noise[mask]
    return ind

def predict_lvq(X, prototypes, proto_labels):

    preds = []

    for x in X:

        distances = np.linalg.norm(prototypes - x, axis=1)

        winner = np.argmin(distances)

        preds.append(proto_labels[winner])

    return np.array(preds)

POP_SIZE = 20
GENERATIONS = 18

population = [create_individual() for _ in range(POP_SIZE)]

for gen in range(GENERATIONS):
    fitnesses = [fitness(ind) for ind in population]

    print(f"Gen {gen} | Best: {max(fitnesses):.4f}")

    selected = selection(population, fitnesses)

    next_pop = []
    for i in range(0, POP_SIZE, 2):
        p1, p2 = selected[i], selected[i+1]

        c1 = mutation(crossover(p1, p2))
        c2 = mutation(crossover(p2, p1))

        next_pop.extend([c1, c2])

    population = next_pop

fitnesses = [fitness(ind) for ind in population]
best_idx = np.argmax(fitnesses)

prototypes = population[best_idx]

prototypes = train_lvq(X_scaled, y, prototypes, proto_labels)

y_pred = predict_lvq(X_scaled, prototypes, proto_labels)

print("Final Accuracy:", accuracy_score(y, y_pred))

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y, y_pred)
print(cm)

import pickle

model = {
    "prototypes": prototypes,
    "proto_labels": proto_labels,
    "scaler": scaler
}

with open("lvq_energy_model.pkl", "wb") as f:
    pickle.dump(model, f)

from google.colab import files
files.download("lvq_energy_model.pkl")

df["predicted_class"] = y_pred

df[["nat_demand","demand_class","predicted_class"]].head()

plt.figure(figsize=(12,5))

plt.plot(df["datetime"][:1000], df["nat_demand"][:1000])

plt.title("Electricity Demand Over Time (Sample)")
plt.xlabel("Time")
plt.ylabel("Demand")

plt.show()